package org.example.backend.Domains;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.example.backend.ValueObjects.Color;

import java.util.List;

/**
 * ArkColors table.
 *
 * Represents a canonical Ark color definition.
 *
 * An Ark color is identified by a fixed in-game color ID and contains
 * display metadata such as a human-readable name and hex color value.
 *
 * This table serves as a reference catalog and is used by dinosaurs
 * to map color region selections to actual colors.
 *
 * Primary key:
 * - colorId: in-game Ark color ID (not auto-generated)
 *
 * Relationships:
 * - dinoColors (One-to-Many): links dinosaurs to this color via region mappings {@link DinoColors}
 *
 * Key fields:
 * - color: embedded value object containing the color name and hex code {@link Color}
 *
 * Constraints / rules:
 * - colorId must be unique and correspond to the Ark in-game color index
 * - Color metadata is static/reference data and not computed
 *
 * Notes:
 * - This entity acts as a lookup/reference table.
 * - Color values are not deleted or modified frequently once defined.
 */
@Data
@Table(name = "ark_colors")
@Entity
@AllArgsConstructor
@NoArgsConstructor
public class ArkColors {

    /**
     * In-game Ark color identifier.
     *
     * This value maps directly to Ark's internal color ID and is not
     * auto-generated by the database.
     */
    @Id
    @Column(name = "color_id")
    private long colorId;

    /**
     * Associations between this color and dinosaur color region assignments.
     *
     * Each entry represents a dinosaur using this color in a specific region.
     */
    @OneToMany(mappedBy = "arkColor")
    @JsonManagedReference("color-dinosaur")
    private List<DinoColors> dinoColors;

    /**
     * Embedded color metadata.
     *
     * Contains:
     * - colorName: display name of the color
     * - colorHex: hex code used for UI rendering
     */
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "colorName", column = @Column(name = "color_name")),
            @AttributeOverride(name = "colorHex", column = @Column(name = "color_hex"))
    })
    private Color color;
}
